modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Xaidee/oreganised/issues/" #optional

[[mods]] #mandatory
modId="oreganized" #mandatory
version="1.19-1.0.3" #mandatory
displayName="Oreganized" #mandatory
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/oreganized/files" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreganized" #optional
logoFile="oreganized.png" #optional
logoBlur=false
itemIcon="oreganized:silver_ore"
configBackground="oreganized:textures/block/glance_bricks.png"
credits="Thanks to our wonderful Patreon members and those who help participate in discussions on our Discord server!" #optional
authors="Xaidee as part of Team Galena" #optional
description='''
Oreganized is a mod focusing on adding new ores and metals to Minecraft. Currently it adds, Lead and Silver as base metals and a new alloy known as Electrum.

This mod is designed to be a Vanilla plus mod while also adding unique uses and abilities to its content rather than just meaningless toolsets for a more engaging experience that tries to match the quality of Mojang's own implementations of new content.
'''

[[dependencies.oreganized]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.oreganized]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
